services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: . # The Dockerfile is in the root of your project
    container_name: gameoflife_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
