name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test --logger trx

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: **/*.trx

  docker-build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t gameoflife-app:latest .

      - name: Push Docker Image
        run: |
            docker tag gameoflife-app:latest your-dockerhub-username/gameoflife-app:latest
            docker push your-dockerhub-username/gameoflife-app:latest

      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: YourResourceGroup
          name: gameoflife-container
          image: your-dockerhub-username/gameoflife-app:latest
          ports: "5000"
